### Delete SERIE
DELETE http://localhost:8081/series/public/api/series/23

### Create SERIE
POST http://localhost:8081/series/public/api/series
Content-Type: application/json

{
    "name": "La série de Michel",
    "genres": "Western",
    "status": "Returning",
    "vote": 8,
    "popularity": 500,
    "firstAirDate": "2026-03-01",
    "lastAirDate": "2026-03-31",
    "backdrop": "backdrop.png",
    "poster": "poster.png",
    "tmbdId": 123456
}

###


###
